# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c029c6cc0ed8d297e5bd2db9f3688a452015f1fdae936e3e46618c5be67052cc10df90ddbe00763471f1ebc679f1d8a6e115f9634c3080d75c8a95f11c668273
  facebook:
    app_id: 1646643982279130
    app_secret: <%= ENV["FACEBOOK_APP_SECRET"]%>
    app_token: 1646643982279130|tWlqP6jb6DORX7jbGlGwIlpF6Gg

test:
  secret_key_base: dce1945872f3875cf0e24783f3d930695fc3c63e1a7249b4315c0e58b309da0d4b047c5b97c7dfa548070ba48db30009ec3d5ca8cb217afb80dd074f6390f3b7
  facebook:
    app_id: 1646643982279130
    app_secret: <%= ENV["FACEBOOK_APP_SECRET"]%>
    app_token: 1646643982279130|tWlqP6jb6DORX7jbGlGwIlpF6Gg

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook:
    app_id: <%= ENV["FACEBOOK_APP_KEY"] %>
    app_secret: <%= ENV["FACEBOOK_APP_SECRET"]%>
    app_token: <%= ENV["FACEBOOK_APP_TOKEN"] %>
